name: Build and ZIP

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Package installations for Backend
        run: npm install
      - name: Package installations for Frontend
        run: |
          cd ./frontend
          npm install
      - name: Build Frontend
        run: |
          cd ./frontend
          npm run build
      - name: Make deployment folder
        run: |
          cd ..
          npm run makeDeploy
      - name: ZIP deployment folder
        run: zip deploy.zip deploy

  
 