name: Build and ZIP
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Package installations for Backend
        run: npm install
      - name: Package installations for Frontend
        run: |
          cd ./frontend
          npm install
      - name: Build Frontend
        run: |
          cd ./frontend
          npm run build

  zip:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create ZIP package
        run: echo "zip the backend files and the frontend/dist folder into a ZIP file"
  another_job:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Do something else after build (parallel with zip?)
        run: echo "Do something else"
