name: Build and ZIP
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Package installations for Backend
        run: npm install
      - name: Package installations for Frontend
        run: |
          cd ./frontend
          npm install --production
      - name: Build Frontend
        run: |
          cd ./frontend
          npm run build
  zip:
    needs: copy
    runs-on: ubuntu-latest
    steps:
      - name: Create ZIP package
        uses: actions/thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: './frontend/*'
  release:
    needs: zip
    runs-on: ubuntu-latest
    steps:
      - name: Upload release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token
 