name: Build and ZIP
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Package installations for Backend
        run: npm install
      - name: Package installations for Frontend
        run: |
          cd ./frontend
          npm install
      - name: Build Frontend
        run: npm build

  zip:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create ZIP package
        run: echo "zip the backend files and the frontend/dist folder into a ZIP file"
  another_job:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Do something else after build (parallel with zip?)
        run: echo "Do something else"
