name: Build and ZIP
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Frontend
        run: echo "npm install on the FE project"
        run: echo "Running the FE build"
      - name: Build Backend
        run: echo "npm install on the BE project"
  zip:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create ZIP package
        run: echo "zip the backend files and the frontend/dist folder into a ZIP file"
