name: Build and ZIP

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

env:
  NODE_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Package installations for Backend
        run: npm install
      - name: Package installations for Frontend
        run: |
          cd ./frontend
          npm install --production
      - name: Build Frontend
        run: |
          cd ./frontend
          npm run build

  zip:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create ZIP package
        run: zip -r release.zip . -x ./frontend

  release:
    needs: zip
    runs-on: ubuntu-latest
    steps:
      - name: Upload release
        run: echo "TODO - There should be a process here..."
 