name: Test deploy

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "0.0.2"
  #   branches:
  #     - "master"

env:
  AZURE_WEBAPP_NAME: mern-auth-app
  AZURE_WEBAPP_DEPLOYZIP: ./deploy.zip
  AZURE_RESOURCEGROUP_NAME: mern-test-rg
  ENVIRONMENT: nonprod

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Sign into Azure
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./bicep/deploy.bicep
          parameters: environmentType=${{ env.ENVIRONMENT }}

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_DEPLOYZIP }}

